In [22]:
import pandas as pd
import difflib
from sqlalchemy import create_engine

In [10]:
gt_df = pd.read_csv('data/GenoTracker.csv', header=1)
gmmb_df = pd.read_csv('data/gmmb_tracker.csv', header=1)
ancestry_df = pd.read_csv('data/FEB_2024_cohort_ancestry_phenotype.csv', header=0)

In [41]:

# def find_best_matches(list1, list2, cutoff=0.6):
#     matches = {}
#     for item in list1:
#         match = difflib.get_close_matches(item, list2, n=1, cutoff=cutoff)
#         if match:
#             matches[item] = match[0]
#         else:
#             matches[item] = None
#     return matches

# best_matches = find_best_matches(gt_df.loc[~gt_df['Study Code'].isna(), 'Study Code'], gmmb_df['Cohort Name'])

# for k, v in best_matches.items():
#     print(f"{k}: {v}")

In [715]:
study_code = "ADPAR"

gt_fields = ['Study Code', 'Individual Study Name', 'Institution', 'City', 'Geographic locality [free text]']
# gt_fields_df = gt_df.loc[gt_df['Study Code']==study_code, gt_fields]
gt_fields_df = gt_df.loc[gt_df['Institution'].str.contains("National Institute of Mental Health", na=False), gt_fields]

gmmb_fields = ['Cohort Name', 'Institution', 'City', 'Country (Location)']
gmmb_fields_df = gmmb_df.loc[gmmb_df["Cohort Name"].str.contains("National Institute of Mental Health and Neurosciences"), gmmb_fields]


print('genotracker')
for index, row in gt_fields_df.iterrows():
    for col_name, value in row.items():
        print(f'{col_name}: {value}')
    print()

print('##'*30)
print()

print('gmmb')
for index, row in gmmb_fields_df.iterrows():
    for col_name, value in row.items():
        print(f'{col_name}: {value}')
    print()
    
print('##'*30)
print()

genotracker
Study Code: NIMH
Individual Study Name: The genetics of REM sleep behavior disorder, parkinson´s disease and other synucleinopathies
Institution: National Institute of Mental Health
City: Prague
Geographic locality [free text]: Czech Republic

############################################################

gmmb
Cohort Name: LUX GIANT - National Institute of Mental Health and Neurosciences
Institution: National Institute of Mental Health and Neurosciences
City: Bangalore
Country (Location): India

############################################################

In [95]:
# gt_name_merge = gt_df[['Study Code','Individual Study Name']].merge(gmmb_df[['Cohort Name']], left_on='Individual Study Name', right_on='Cohort Name')
# for index, row in gt_name_merge.iterrows():
#     print(f'Row {index}')
#     for col_name, value in row.items():
#         print(f" {col_name}: {value}")

In [716]:
cohort_mapping = {
    "BCM": "Baylor College of Medicine (BCM)",
    "CORIELL": "CORIELL",
    "PDGNRTN": "PDGENEration",
    "UMD": "BCM-UMD",
    "PROSPOS": "PROSPOS",
    "SP-SEV": "Sp_SEV - HUVR/CSIC/Universidad de Sevill",
    "COPN": "C-OPN",
    "NZP3": "Christchurch Longitudinal Parkinson's Study",
    "UPENNU19": "UPENN U19 Cohort",
    "BADGEPD": "BADGE-PD",
    "CAMPAIGN": "CamPaIGN",
    "DIGPD": "DIGPD",
    "ICEBERG": "ICEBERG",
    "IDCME": "NGC",
    "MIND": "MIND Initiative",
    "NSPARK": "NS PARK",
    "PICNICS": "PICNICS",
    "PREDISTIM": "PREDICT-PD",
    "QPN": "Quebec Parkinson's Network",
    "RBM": "RBM",
    "SP-BCN3": "Sp_BCN3 - Sant Joan de Déu",
    "SP-OVI": "Sp_OVI - University of Oviedo",
    "MDGAP-KINGS": "MD GAP - King's College London",
    "MDGAP-QSBB": "MD GAP - QSBB - University College London",
    "POM": "POM",
    "LCC": "LCC",
    "UMKLM": "Malaysian Parkinson's Genetics Cohort - UMKLM",
    "GPARKGR": "GenePARKGR",
    "PROPARK": "ProPark",
    "SP-BCN2": "Sp_BCN2 - University Hospital Mútua de Terrassa",
    "SP-SNT": "Sp_SNT - University Hospital Marques de Valdecilla-IDIVAL",
    "BIOFIND": "BioFIND",
    "BLAACPD-KPM": "BLAACPD - Kaiser Permanente",
    "BLAACPD-RUSH": "BLAACPD - Rush University",
    "BLAACPD-UAB": "BLAACPD - University of Alabama at Birmingham",
    "BLAACPD-UC": "BLAACPD - University of Chicago",
    "CALYPSO": "CALYPSO",
    "MDGAP-EBB": "MD GAP - Edinburgh Brain Bank - University of Edinburgh",
    "PFP": "PFP",
    "PPMI": "PPMI",
    "PROBAND": "PROBAND",
    "SYNAPS-KZ": "SYNAPS-KZ",
    "VIPD": "VIPD",
    "CANDAS": "CANDAS",
    "QPP": "QPP",
    "UGUPD": "UGCPD",
    "GENEFINDER": "GeneFinder",
    "OPDC": "OPDC Discovery Cohort",
    "MDGAP-MBB": "Manchester Brain Bank",
    "PROMO": "ProtectMove - Institute of Neurogenetics, University of Lübeck",
    "PROATYP": "proATYP",
    "MDGAP-IBB": "PUKBB",
    "BENHAMIDA": "Clinicogenetic Study of PD in Tunisia",
    "ELPD": "ELPD Project",
    "PDSGR": "PDS",
    "PREDICTPD": "PREDICT-PD",
    "AUTH": "AUTH - GP2 study",
    "PDSTAT": "PD STAT",
    "MPBC": "MPBC",
    "SYDPDRC": "Sydney PDRC",
    "APGS": "APGS",
    "SYDBB": "Sydney Brain Bank - SYDBB",
    "CPRC": "Cambridge Parkinson's Research Clinic",
    "IPDGCEA-JKU": "IPDGC East Asia - Jikei University",
    "ADEPTPD": "ADepT-PD",
    "PDMDC": "PDMDC/NUgene",
    "GARVAN": "Genetic analysis in inherited neurological disorders",
    "KUL": "Genotype-Phenotype Correlations in PD and Related Movement Disorders - KUL",
    "PDMDCB": "Parkinson Disease and Movement Disorders Center Biorepository",
    "TUEPAC": "Tuepac + TREND",
    "LUXPARK": "LUX-Park",
    "BIOPARK": "To be updated - Karolinska Institutet",
    "IMMLISBON": "Movement Disorders Biobanc",
    "PDGEN": "PDGENEration",
    "DATATOP": "DATATOP",
    "SZTE": "SZTE",
    "TRD": "Trondheim Study",
    "MDGAP-SW": "MD GAP - South West Dementia Brain Bank - Southmead Hospital",
    "S4": "S4",
    "NETPDLS1": "NET-PD",
    "DENOPA": "DeNoPa",
    "NTUH": "Genomewide Association Study in PD among East Asians - NTUH",
    "BRFAA": "Biological markers in Parkinson's disease - BRFAA",
    "BUE": "BUE - GP2",
    "LARGEPD": "To be updated - Cleveland Clinic",
    "BBDP": "Arizona Brain Bank Brain and body donation programme (BBDP)",
    "CINCINNATI": "Clinical and genetic study of Unusual/Familial Movement Disorders",
    "MMCTU": "Genotype-Phenotype Correlations in Nepalese PD Population - MMCTU",
    "PERUGIA": "CSF Biomarkers",
    "STELLENBOS": "Genetic study of PD and related movement disorders",
    "CHULALONGK": "Genetic Testing in Patients with Movement Disorders and PD",
    "MDGAP-NWCSTL": "MD GAP - Newcastle Brain Bank - University of Newcastle",
    "KFSH": "The Molecular Basis of Movement Disorders in Saudis - KFSH",
    "PAGE": "PAGE",
    "SYNAPS-GR": "SYNAPS-GR",
    "PDCARE": "PDCARE",
    "RAPSODI": "RAPSODI",
    "YOPDFL": "YOPDFL (Young Onset Parkinson's Disease)",
    "FDSANTIAGO": "GP2 - Fundación Diagnosis",
    "MULODZ": "Molecular Testing of Polish PD Patients",
    "TONIC-PERRON": "TONiC PD",
    "KOC": "GP2 - Koc University",
    "JGUM": "JGUM",
    "PATRAS": "PATRAS",
    "NUGENE": "NU Gene",
    "CDPDGR": "Thessaly PD Database",
    "JENPARK": "Jena Parkinson Study",
    "UROMETV": "Standardized data collection of PD patients",
    "CHCHPD": "Christchurch Longitudinal Parkinson's Study",
    "HIPDR": "HIPDR",
    "KOLLING": "Kolling PD",
    "SEOULNUH": "GP2 - Seoul National University Hospital",
    "NROSF2U": "Multicentric Retrospective and Prospective PD Database",
    "BLAACPD-LSU": "BLAACPD - Louisiana State University",
    "IMMUNEPD": "Innate and Adaptive Immunity in PD",
    "PROMO-EPIPARK": "PROMO-EPIPARK",
    "PROMO-GENEPARK": "PROMO-GENEPARK",
    "PROMO-ROPAD": "PROMO-ROPAD",
    "PROMO-SFB134": "PROMO-SFB134",
    "PROMO-SYSMED": "PROMO-SYSMEDPD",
    "OXQUIP": "Oxford Study of Quantification in Parkinsonism",
    "PROMO-USTP": "PROMO-USTP",
    "MUVIENNA": "Families with Neurodegenerative Diseases",
    "CATANZARO": "Familial and Early-onset PD Database",
    "QMAP": "Quantitative MRI for Anatomical Phenotyping in Parkinson's Disease",
    "CATPD": "Central Asian and Transcaucasian PD (CAT-PD)",
    "IPDGCAF-NG": "IPDGC Africa - The Nigerian Parkinson Disease Research Network",
    "IPDGCEA-JU": "IPDGC East Asia - Juntendo University",
    "TUMBB": "Biobank for Diseases of the Peripheral and Central Nervous System - TUMBB",
    "TUMPD": "Genetics of Parkinson's Disease - TUMPD",
    "ANANEOS": "ANANEOS Study",
    "MDGAP-CAMBRIDGE": "MD GAP - Cambridge",
    "MDGAP-OXF": "MD GAP - OXF",
    "VETPD": "VET-PD",
    "BERNGEN": 'BERN',
    "SINAI": 'Mount Sinai Cohort',
    "PARKWEST": "The Norwegian Parkwest Study",
    "PROSPECT": "PROSPECT",
    "UMUDALL": "UMUDALL",
    "TORONTO": "To be updated - University of Toronto",
    "MDGAP-VBB": "MD GAP - Victorian Brain Bank",
    "IRCCSN": "Genetics of Neurological Pathologies: New Variations, New Phenotypes",
    "PROBEPD": "PROBEPD",
    "TLVMC": "DLB Cohort TLVMC",
    "ANDPD": "ANDPD",    
    "MONPAR": "Genetic Study for Pakinson's Disease in Mongolia",
    "NGIPDO": "NGIPDO - Neurogenomics and Informatics Center - Parkinson's Disease  Deep Molecular Profiling",
    "IPDGCEA-UKM": "IPDGC East Asia - UKM",
    "DODONA": "The DodoNa Project: DNA Predictions to Improve Neurological Health",
    "PROMO-CARRIERS": "PROMO-CARRIERS",
    "HAWAIIPD": "HAWAII PD",
    "YMS": "Yale Medical School",
    "IGECND": "IGECND",
    "DHAKA": "GP2 - Bangladesh",
    "UGCPD": "UGCPD",
    "AAPDGC": "AfrAbia-PD Genomic Consortium (AA-PDGC)",
    "REGARDS": "REasons for Geographic and Racial Differences in Stroke (REGARDS) Project",
    "NZPEGS": "New Zealand Parkinson's Environment and Genes Study",
    "GPX": "GenePool Study",
    "VAIBB": "Van Andel Institute Brain Bank",
    "WEHI": "WEHI - Integrating molecular and omics approaches in Parkinson’s disease",
    "ACCESSPD": "ACCESSPD",
    "GPS": "GenePool Study",
    "NGP": "The Neuro Genomics Partnership",
    "SCANPSP": "SCANPSP - Study of Comprehensive ANd Multimodal Marker-based Cohort of PSP",
    "SAMSUNG": "GP2 - Samsung",
    "BURGOS": "Local Study - Burgos",    
    "SP-DON": None,
    "ECMPDC": None,
    "SP-GRANADA": None,
    "AHEPA": None,
    "CIDR": None,
    "INKOSI": None,
    "SP-BCN1": None,
    "SANGERARDO": None,
    "GEMELLI": None,
    "NMDAT": None,
    "TARTU": None,
    "TEHRAN": None,
    "KIEL": None,
    "YAGUE": None,
    "MAYO": None,
    "AMSBB": None,
    "PDSA": None,
    "RDIPD": None,
    "ANKARA": None,
    "DUPARC": None,
    "ESTBB": None,
    "PUJBC": None,
    "CMC": None,
    "SAREMA": None,
    "IPDGCEA-MU": None,
    "AARHUS": None,
    "CEGEMOD": None,
    "JUNT": None,
    "HSPH": None,
    "NGRC": None,
    "SILESIA": None,
    "KRAKOW": None,
    "BRNO": None,
    "COLOMBO": None,
    "ADRC": None,
    "SILAD": None,
    "STANPD": None,
    "GENNIS": None,
    "AHS": None,
    "IDIBAPS": None,
    "FLENI": None,
    "EPIC": None,
    "CCFPD": None,
    "GRACE": None,
    "NYSCF": None,
    "PARS": None,
    "PEG": None,
    "SAMC": None,
    "SAUD": None,
    "COBB": None,
    "PDCGC": None,
    "SANTPAU": None,
    "TRAPCAF": None,
    "NITHAI": None,
    "RTGRS": None,
    "PROGENI": None,
    "BIOPD": None,
    "BOLOGNA": None,
    "BPS": None,
    "CABBS": None,
    "CLGN": None,
    "CUHK": None,
    "GENCI": None,
    "HEBA-BRC": None,
    "HEBA-INNS": None,
    "HEBA-KASSEL": None,
    "INECO": None,
    "INNS": None,
    "MONT": None,
    "NORTHSHORE": None,
    "PARAGEN": None,
    "FAIRPARK": None,
    "PROLBD": None,
    "RIMU": None,
    "PARAGEN-MON": None,
    "UCIPARK": None,
    "GBA1NL": None,
    "PDNEF": None,
    "UCIPROS": None,
    "NHGRI": None,
    "CAGL": None,
    "REMANT": None,
    "REMEL": None,
    "UDINE": None,
    "REMEDIO": None,
    "PAIR-PSP": None,
    "PDBIOMARKERS": None,
    "NAFPD": None,
    "FNPREG": None,
    "GED": None,
    "PDGEN-CLEM": None,
    "MDGAP-DEMENTIA": None,
    "EXENATIDEPD3": None,
    "GPDC": None,
    "NORBANK": None,
    "NYBB": None,
    "NYPUM/PARKNY": None,
    "UWBRAIN": None,
    "SUREPD2": None,
    "UNIBS": None,
    "IUC": None,
    "CANDAS-SMPD": None,
    "CANDAS-PDGEN": None,
    "EMORY": None,
    "CANPARK": None,
    "TAS": None,
    "ISLAND": None,
    "PPRBD": None,
    "CRUCES": None,
    "NRIBBB": None,
    "NBB-HVD": None,
    "NBB-SINAI": None,
    "NBB-SPLVD": None,
    "NBB-MLND": None,
    "NBB-MIAMI": None,
    "NBB-PBG": None,
    "BELGRADE": None,
    "MHHBB": None,
    "SLOWSPEED": None,
    "FMGC": None,
    "IRAMS": None,
    "GENOT": None,
    "UTSW": None,
    "ADPAR": None,
    "NIMH": None,
    }

In [39]:
df = pd.read_csv('data/GenoTracker.csv', header=1)
df_sub = df.loc[:,[
    "Study Code",
    "Monogenic / Complex / Mixed",
    "City",
    "Geographic locality [free text]",
    "DNA samples attempted [N]",
    "Total samples passing basic QC [N]",
    "Failed call rates [N < 95%]",
    "Failed sex check [N with contradictory reported versus genetic sex]",
    "Failed contamination and heterozygosity checks [N, outliers for ancestry specific heterozygosity rates]",
    "Duplicate samples [N, IBD estiamtes > 95%]",
    "African (AFR)",
    "African admixed (AAC)",
    "Ashkenzai (AJ)",
    "East Asian (EAS)",
    "European (EUR)",
    "Finnish (FIN)",
    "LatinX (AMR)",
    "South Asian (SAS)",
    "Central Asian (CAS)",
    "Middle Eastern (MDE)",
    "Complex Admixture (CAH)",
    "Total",
    "Imputation panels(s) [Free text]",
    "Imputation complete for current samples [0 = no, 1 = yes]",
    "Full data [0 = only summary stats, 1 = genotypes sharable]",
    "GDPR [0 = no European restriction, 1 = limited by GDPR]",
    "Site [NIH, Tubingen/DZNE, Fulgent, UCL]"
]]

rename_dict = {
    "Study Code": "study_code",
    "Monogenic / Complex / Mixed": "monogenic_complex_mixed",
    "City": "city",
    "Geographic locality [free text]": "geographic_locality",
    "DNA samples attempted [N]": "n_dna_samples_attempted",
    "Total samples passing basic QC [N]": "total_qc_pass",
    "Failed call rates [N < 95%]": "callrate_fails",
    "Failed sex check [N with contradictory reported versus genetic sex]": "sex_fails",
    "Failed contamination and heterozygosity checks [N, outliers for ancestry specific heterozygosity rates]": "het_fails",
    "Duplicate samples [N, IBD estiamtes > 95%]": "duplicates",
    "African (AFR)": "AFR",
    "African admixed (AAC)": "AAC",
    "Ashkenzai (AJ)": "AJ",
    "East Asian (EAS)": "EAS",
    "European (EUR)": "EUR",
    "Finnish (FIN)": "FIN",
    "LatinX (AMR)": "AMR",
    "South Asian (SAS)": "SAS",
    "Central Asian (CAS)": "CAS",
    "Middle Eastern (MDE)": "MDE",
    "Complex Admixture (CAH)": "CAH",
    "Total": "total",
    "Imputation panels(s) [Free text]": "imputation_panel",
    "Imputation complete for current samples [0 = no, 1 = yes]": "imputation_complete",
    "Full data [0 = only summary stats, 1 = genotypes sharable]": "genotypes_shareable",
    "GDPR [0 = no European restriction, 1 = limited by GDPR]": "gdpr",
    "Site [NIH, Tubingen/DZNE, Fulgent, UCL]": "site"
}

df_sub.rename(columns=rename_dict, inplace=True)

df_out = df_sub.fillna({
    'study_code': '',
    'monogenic_complex_mixed': '',
    'city': '',
    'geographic_locality': '',
    'n_dna_samples_attempted': 0,
    'total_qc_pass': 0,
    'callrate_fails': 0,
    'sex_fails': 0,
    'het_fails': 0,
    'duplicates': 0,
    'AFR': 0,
    'AAC': 0,
    'AJ': 0,
    'EAS': 0,
    'EUR': 0,
    'FIN': 0,
    'AMR': 0,
    'SAS': 0,
    'CAS': 0,
    'MDE': 0,
    'CAH': 0,
    'total': 0,
    'genotypes_shareable': 0,
    'imputation_complete': 0,
    'imputation_panel': '',
    'gdpr': 0,
    'site': ''
})

numeric_columns = [
    'n_dna_samples_attempted', 'total_qc_pass', 'callrate_fails', 'sex_fails', 
    'het_fails', 'duplicates', 'AFR', 'AAC', 'AJ', 'EAS', 'EUR', 'FIN', 
    'AMR', 'SAS', 'CAS', 'MDE', 'CAH', 'total', 'genotypes_shareable', 
    'imputation_complete', 'gdpr'
]

df_out[numeric_columns] = df_out[numeric_columns].astype(int)
df_out.to_csv('data/genotracker_clean.csv', index=False)

In [55]:
ancestry_df = pd.read_csv('data/FEB_2024_cohort_ancestry_phenotype.csv')
ancestry_df.rename(columns={'Cohort':'study_code'}, inplace=True)
df_out.merge(ancestry_df, on='study_code', how='right')

,study_code,monogenic_complex_mixed,city,geographic_locality,n_dna_samples_attempted,total_qc_pass,callrate_fails,sex_fails,het_fails,duplicates,...,CAS Case,CAS Control,CAS Other,MDE Case,MDE Control,MDE Other,CAH Case,CAH Control,CAH Other,Total
0,AUTH,Complex,Thessaloniki,Greece,88,88,0,0,0,0,...,0,0,0,4,0,0,0,0,0,176
1,CATPD,Complex,0,Asia/Oceania,665,633,14,13,0,5,...,268,50,2,12,183,2,22,24,0,1268
2,DODONA,Mixed,Chicago,United States,747,722,16,1,0,7,...,1,0,0,8,0,0,2,0,0,1456
3,JGUM,Complex,Munich / Mainz,Germany,564,559,0,4,0,1,...,1,1,0,13,1,0,4,1,0,1120
4,MDGAP-EBB,Complex,"Edinburgh, London",UK,212,176,28,6,0,2,...,0,0,0,0,0,0,0,0,0,62
5,MDGAP-IBB,Mixed,London,UK,386,350,12,21,0,2,...,0,0,0,0,0,0,0,0,0,926
6,MDGAP-OXF,Complex,Oxford,UK,41,10,0,31,0,0,...,0,0,1,0,0,0,0,0,0,350
7,MDGAP-QSBB,Complex,London,UK,1194,1021,55,85,0,16,...,0,0,0,0,0,0,0,0,0,608
8,MDGAP-SW,Complex,Bristol,England,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,232
9,NZPEGS,Mixed,Christchurch,New Zealand,345,329,15,1,0,0,...,0,0,0,0,0,0,0,0,0,658
10,PDGNRTN,Mixed,"Miami, FL",USA,4694,3791,239,352,0,296,...,6,0,0,4,0,0,29,0,0,2972
11,PERUGIA,Mixed,Perugia,Italy,100,93,0,7,0,0,...,0,0,0,0,0,0,0,0,0,186
12,PROBAND,Mixed,Glasgow,UK,41,39,1,0,0,1,...,0,0,0,0,0,0,0,0,0,80
13,PROSPECT,Complex,London,England,299,212,16,66,0,5,...,0,0,0,0,0,0,0,0,1,334
14,RAPSODI,Complex,London,UK,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,188
15,REGARDS,Complex,Birmingham,United States,5587,5370,113,57,0,5,...,0,0,0,0,1,0,0,2,0,1746

In [45]:


# Create an engine instance
engine = create_engine('sqlite:///test.db')

# Query to select all data from the genetic_data table
query = "SELECT * FROM genetic_data"

# Execute the query and load the data into a pandas DataFrame
df = pd.read_sql(query, engine)

# Display the first few rows of the DataFrame
print(df.head())

# Display summary statistics
print(df.describe())

# Display the data types of the columns
print(df.dtypes)

# Filter the data
df_filtered = df[df['city'] == 'Boulder']
print(df_filtered.head())

# # Plot the data
# import matplotlib.pyplot as plt

# df['n_dna_samples_attempted'].hist()
# plt.xlabel('Number of DNA Samples Attempted')
# plt.ylabel('Frequency')
# plt.title('Distribution of DNA Samples Attempted')
# plt.show()

   id study_code monogenic_complex_mixed           city geographic_locality  \
0   1        BCM                 Complex     Houston,TX                 USA
1   2    CORIELL                 Complex     Camden, NJ                 USA
2   3    PDGNRTN                   Mixed     Miami, FL                  USA
3   4        UMD                 Complex  Baltimore, MD                 USA
4   5    PROSPOS                 Complex           Oslo              Norway

   n_dna_samples_attempted  total_qc_pass  callrate_fails  sex_fails  \
0                      809            788               7         12
1                     8982           8718             140         56
2                     4694           3791             239        352
3                      479            441               6         15
4                       96             95               0          1

   het_fails  ...  CAS  MDE  CAH  total  genotyping_complete  \
0          0  ...    5    4    5    788                    0
1          1  ...    8   48  167   8718                    0
2          0  ...   16   21  174   3791                    0
3          0  ...    2    2    2    441                    0
4          0  ...    0    0    0     95                    0

   imputation_panel  imputation_complete  genotypes_shareable  gdpr     site
0            TOPMED                    1                    1     0      NIH
1            TOPMED                    1                    1     0      NIH
2            TOPMED                    1                    1     0  Fulgent
3            TOPMED                    1                    1     0      NIH
4            TOPMED                    1                    1     1  Fulgent

[5 rows x 29 columns]
               id  n_dna_samples_attempted  total_qc_pass  callrate_fails  \
count  311.000000               311.000000     311.000000      311.000000
mean   156.000000               189.302251     175.440514        5.173633
std     89.922189               761.131042     716.178651       24.136081
min      1.000000                 0.000000       0.000000        0.000000
25%     78.500000                 0.000000       0.000000        0.000000
50%    156.000000                 0.000000       0.000000        0.000000
75%    233.500000                19.000000      18.500000        0.000000
max    311.000000              8982.000000    8718.000000      239.000000

        sex_fails   het_fails  duplicates          AFR         AAC  \
count  311.000000  311.000000  311.000000   311.000000  311.000000
mean     4.427653    0.009646    3.559486     8.501608    3.578778
std     22.928650    0.097898   20.679010    91.034339   41.613731
min      0.000000    0.000000    0.000000     0.000000    0.000000
25%      0.000000    0.000000    0.000000     0.000000    0.000000
50%      0.000000    0.000000    0.000000     0.000000    0.000000
75%      0.000000    0.000000    0.000000     0.000000    0.000000
max    352.000000    1.000000  296.000000  1403.000000  723.000000

               AJ  ...         AMR         SAS         CAS         MDE  \
count  311.000000  ...  311.000000  311.000000  311.000000  311.000000
mean     8.562701  ...    2.099678    2.073955    2.906752    1.871383
std     62.169345  ...   15.717251   12.055423   28.430918   12.646159
min      0.000000  ...    0.000000    0.000000    0.000000    0.000000
25%      0.000000  ...    0.000000    0.000000    0.000000    0.000000
50%      0.000000  ...    0.000000    0.000000    0.000000    0.000000
75%      0.000000  ...    0.000000    0.000000    0.000000    0.000000
max    780.000000  ...  195.000000  142.000000  366.000000  197.000000

              CAH        total  genotyping_complete  imputation_complete  \
count  311.000000   311.000000                311.0           311.000000
mean     2.742765   175.440514                  0.0             0.257235
std     22.141293   716.178651                  0.0             0.437814
min      0.000000     0.000000                  0.0             0.000000
25%      0.000000     0.000000                  0.0             0.000000
50%      0.000000     0.000000                  0.0             0.000000
75%      0.000000    18.500000                  0.0             1.000000
max    299.000000  8718.000000                  0.0             1.000000

       genotypes_shareable        gdpr
count           311.000000  311.000000
mean              0.334405    0.202572
std               0.472542    0.402564
min               0.000000    0.000000
25%               0.000000    0.000000
50%               0.000000    0.000000
75%               1.000000    0.000000
max               1.000000    1.000000

[8 rows x 23 columns]
id                          int64
study_code                 object
monogenic_complex_mixed    object
city                       object
geographic_locality        object
n_dna_samples_attempted     int64
total_qc_pass               int64
callrate_fails              int64
sex_fails                   int64
het_fails                   int64
duplicates                  int64
AFR                         int64
AAC                         int64
AJ                          int64
EAS                         int64
EUR                         int64
FIN                         int64
AMR                         int64
SAS                         int64
CAS                         int64
MDE                         int64
CAH                         int64
total                       int64
genotyping_complete         int64
imputation_panel           object
imputation_complete         int64
genotypes_shareable         int64
gdpr                        int64
site                       object
dtype: object
Empty DataFrame
Columns: [id, study_code, monogenic_complex_mixed, city, geographic_locality, n_dna_samples_attempted, total_qc_pass, callrate_fails, sex_fails, het_fails, duplicates, AFR, AAC, AJ, EAS, EUR, FIN, AMR, SAS, CAS, MDE, CAH, total, genotyping_complete, imputation_panel, imputation_complete, genotypes_shareable, gdpr, site]
Index: []

[0 rows x 29 columns]

In [46]:
df

,id,study_code,monogenic_complex_mixed,city,geographic_locality,n_dna_samples_attempted,total_qc_pass,callrate_fails,sex_fails,het_fails,...,CAS,MDE,CAH,total,genotyping_complete,imputation_panel,imputation_complete,genotypes_shareable,gdpr,site
0,1,BCM,Complex,"Houston,TX",USA,809,788,7,12,0,...,5,4,5,788,0,TOPMED,1,1,0,NIH
1,2,CORIELL,Complex,"Camden, NJ",USA,8982,8718,140,56,1,...,8,48,167,8718,0,TOPMED,1,1,0,NIH
2,3,PDGNRTN,Mixed,"Miami, FL",USA,4694,3791,239,352,0,...,16,21,174,3791,0,TOPMED,1,1,0,Fulgent
3,4,UMD,Complex,"Baltimore, MD",USA,479,441,6,15,0,...,2,2,2,441,0,TOPMED,1,1,0,NIH
4,5,PROSPOS,Complex,Oslo,Norway,96,95,0,1,0,...,0,0,0,95,0,TOPMED,1,1,1,Fulgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,FMGC,Mixed,Bordeaux,France,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
307,308,IRAMS,Mixed,Bordeaux,France,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
308,309,GENOT,Mixed,Tunis,Tunisia,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
309,310,UTSW,Mixed,Dallas,United States,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
310,311,ADPAR,Mixed,Bucharest,Romania,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [49]:
df_out.study_code.value_counts()

study_code
0             19
BCM            1
EPIC           1
IDIBAPS        1
AHS            1
              ..
CHULALONGK     1
STELLENBOS     1
PERUGIA        1
MMCTU          1
ADPAR          1
Name: count, Length: 293, dtype: int64

In [50]:
df_out.loc[df_out.study_code=='0']

,study_code,monogenic_complex_mixed,city,geographic_locality,n_dna_samples_attempted,total_qc_pass,callrate_fails,sex_fails,het_fails,duplicates,...,SAS,CAS,MDE,CAH,total,imputation_panel,imputation_complete,genotypes_shareable,gdpr,site
26,0,Complex,Edinburgh,UK,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
98,0,Monogenic,Sulawesi,Indonesia,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,DZNE
99,0,Monogenic,Ankara,Turkey,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,0,Monogenic,Moscow,Russia,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
112,0,Mixed,London,UK,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Lubeck
115,0,Complex,Newcastle,UK,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
116,0,Complex,Newcastle,UK,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
156,0,Monogenic,Wilrijk,Belgium,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,DZNE
158,0,Monogenic,Tel-Aviv,Israel,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
162,0,Monogenic,Strasbourg,France,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
165,0,Monogenic,Auckland,New Zealand,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
180,0,Monogenic,Cebu,Philippines,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"NIH, Lubeck"
181,0,Monogenic,Jakarta,Indonesia,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Lubeck
185,0,Monogenic,Vienna,Austria,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
190,0,Complex,0,0,0,22,0,0,0,0,...,0,0,0,0,22,0,0,0,0,DZNE
210,0,Monogenic,Parma,Italy,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
233,0,Monogenic,Milan,Italy,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Lubeck
269,0,Monogenic,Messin,Italy,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
276,0,0,Bishkek,Kyrgyzstan,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0