In [1]:
import pandas as pd

In [39]:
df = pd.read_csv('data/GenoTracker.csv', header=1)
df_sub = df.loc[:,[
    "Study Code",
    "Monogenic / Complex / Mixed",
    "City",
    "Geographic locality [free text]",
    "DNA samples attempted [N]",
    "Total samples passing basic QC [N]",
    "Failed call rates [N < 95%]",
    "Failed sex check [N with contradictory reported versus genetic sex]",
    "Failed contamination and heterozygosity checks [N, outliers for ancestry specific heterozygosity rates]",
    "Duplicate samples [N, IBD estiamtes > 95%]",
    "African (AFR)",
    "African admixed (AAC)",
    "Ashkenzai (AJ)",
    "East Asian (EAS)",
    "European (EUR)",
    "Finnish (FIN)",
    "LatinX (AMR)",
    "South Asian (SAS)",
    "Central Asian (CAS)",
    "Middle Eastern (MDE)",
    "Complex Admixture (CAH)",
    "Total",
    "Imputation panels(s) [Free text]",
    "Imputation complete for current samples [0 = no, 1 = yes]",
    "Full data [0 = only summary stats, 1 = genotypes sharable]",
    "GDPR [0 = no European restriction, 1 = limited by GDPR]",
    "Site [NIH, Tubingen/DZNE, Fulgent, UCL]"
]]

rename_dict = {
    "Study Code": "study_code",
    "Monogenic / Complex / Mixed": "monogenic_complex_mixed",
    "City": "city",
    "Geographic locality [free text]": "geographic_locality",
    "DNA samples attempted [N]": "n_dna_samples_attempted",
    "Total samples passing basic QC [N]": "total_qc_pass",
    "Failed call rates [N < 95%]": "callrate_fails",
    "Failed sex check [N with contradictory reported versus genetic sex]": "sex_fails",
    "Failed contamination and heterozygosity checks [N, outliers for ancestry specific heterozygosity rates]": "het_fails",
    "Duplicate samples [N, IBD estiamtes > 95%]": "duplicates",
    "African (AFR)": "AFR",
    "African admixed (AAC)": "AAC",
    "Ashkenzai (AJ)": "AJ",
    "East Asian (EAS)": "EAS",
    "European (EUR)": "EUR",
    "Finnish (FIN)": "FIN",
    "LatinX (AMR)": "AMR",
    "South Asian (SAS)": "SAS",
    "Central Asian (CAS)": "CAS",
    "Middle Eastern (MDE)": "MDE",
    "Complex Admixture (CAH)": "CAH",
    "Total": "total",
    "Imputation panels(s) [Free text]": "imputation_panel",
    "Imputation complete for current samples [0 = no, 1 = yes]": "imputation_complete",
    "Full data [0 = only summary stats, 1 = genotypes sharable]": "genotypes_shareable",
    "GDPR [0 = no European restriction, 1 = limited by GDPR]": "gdpr",
    "Site [NIH, Tubingen/DZNE, Fulgent, UCL]": "site"
}

df_sub.rename(columns=rename_dict, inplace=True)

df_out = df_sub.fillna({
    'study_code': '',
    'monogenic_complex_mixed': '',
    'city': '',
    'geographic_locality': '',
    'n_dna_samples_attempted': 0,
    'total_qc_pass': 0,
    'callrate_fails': 0,
    'sex_fails': 0,
    'het_fails': 0,
    'duplicates': 0,
    'AFR': 0,
    'AAC': 0,
    'AJ': 0,
    'EAS': 0,
    'EUR': 0,
    'FIN': 0,
    'AMR': 0,
    'SAS': 0,
    'CAS': 0,
    'MDE': 0,
    'CAH': 0,
    'total': 0,
    'genotypes_shareable': 0,
    'imputation_complete': 0,
    'imputation_panel': '',
    'gdpr': 0,
    'site': ''
})

numeric_columns = [
    'n_dna_samples_attempted', 'total_qc_pass', 'callrate_fails', 'sex_fails', 
    'het_fails', 'duplicates', 'AFR', 'AAC', 'AJ', 'EAS', 'EUR', 'FIN', 
    'AMR', 'SAS', 'CAS', 'MDE', 'CAH', 'total', 'genotypes_shareable', 
    'imputation_complete', 'gdpr'
]

df_out[numeric_columns] = df_out[numeric_columns].astype(int)
df_out.to_csv('data/genotracker_clean.csv', index=False)

In [34]:
df_out.imputation_panel.value_counts()

imputation_panel
NA        231
TOPMED     80
Name: count, dtype: int64

In [36]:
df_out

,study_code,monogenic_complex_mixed,city,geographic_locality,n_dna_samples_attempted,total_qc_pass,callrate_fails,sex_fails,het_fails,duplicates,...,SAS,CAS,MDE,CAH,total,imputation_panel,imputation_complete,genotypes_shareable,gdpr,site
0,BCM,Complex,"Houston,TX",USA,809,788,7,12,0,2,...,13,5,4,5,788,TOPMED,1,1,0,NIH
1,CORIELL,Complex,"Camden, NJ",USA,8982,8718,140,56,1,40,...,40,8,48,167,8718,TOPMED,1,1,0,NIH
2,PDGNRTN,Mixed,"Miami, FL",USA,4694,3791,239,352,0,296,...,45,16,21,174,3791,TOPMED,1,1,0,Fulgent
3,UMD,Complex,"Baltimore, MD",USA,479,441,6,15,0,17,...,5,2,2,2,441,TOPMED,1,1,0,NIH
4,PROSPOS,Complex,Oslo,Norway,96,95,0,1,0,0,...,0,0,0,0,95,TOPMED,1,1,1,Fulgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,FMGC,Mixed,Bordeaux,France,0,0,0,0,0,0,...,0,0,0,0,0,,0,0,0,
307,IRAMS,Mixed,Bordeaux,France,0,0,0,0,0,0,...,0,0,0,0,0,,0,0,0,
308,GENOT,Mixed,Tunis,Tunisia,0,0,0,0,0,0,...,0,0,0,0,0,,0,0,0,
309,UTSW,Mixed,Dallas,United States,0,0,0,0,0,0,...,0,0,0,0,0,,0,0,0,
310,ADPAR,Mixed,Bucharest,Romania,0,0,0,0,0,0,...,0,0,0,0,0,,0,0,0,

In [40]:
df

,Date,Updater,Study Code,Individual Study Name,Institution,Monogenic / Complex / Mixed,if Mixed: estimated proportion in Monogenic,City,Geographic locality [free text],PI,...,Predicted # DLB by 2028,Predicted # CBS by 2028,Predicted # Prodromal by 2028,Predicted # Other atypical Parkinsonism cases by 2028,Cohort to be WGSd\nYes = 1\nNo = 0,WGS important notes,Sequenced samples [N],Samples passed WGS QC [N],"Shared to AMP-PD [0 = no, 1 = yes].1",Notes [free text]
0,2021-02-09,Hirotaka.I,BCM,Baylor College of Medicine (BCM),Baylor College of Medicine,Complex,NaN,"Houston,TX",USA,Josh Shulman,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
1,2021-02-09,Hirotaka.I,CORIELL,CORIELL,NaN,Complex,NaN,"Camden, NJ",USA,Cornelis Blauwendraat,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2,2021-02-09,Hirotaka.I,PDGNRTN,PDGENEration,Parkinson's Foundation,Mixed,NaN,"Miami, FL",USA,Roy Alcalay,...,NaN,NaN,NaN,NaN,NaN,NaN,255.0,235.0,1.0,NaN
3,2021-02-09,Hirotaka.I,UMD,UMD,University of Maryland,Complex,NaN,"Baltimore, MD",USA,Lisa Shulman,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
4,2021-03-03,Hirotaka.I,PROSPOS,PROSPOS,Oslo University Hospital,Complex,NaN,Oslo,Norway,Lasse Pihlstrøm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,2024-05-08,Simona Jasaityte,FMGC,French MSA genetic cohort,Bordeaux University Hospital,Mixed,NaN,Bordeaux,France,Wassilios Meissner,...,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN
307,2024-05-08,Simona Jasaityte,IRAMS,Etude de l’insulino-résistance dans l’atrophie...,Bordeaux University Hospital,Mixed,NaN,Bordeaux,France,Wassilios Meissner,...,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN
308,2024-05-08,Simona Jasaityte,GENOT,Genetic factors associated with the penetrance...,"Department of Neurology, Razi Hospital, Tunis;...",Mixed,NaN,Tunis,Tunisia,Riadh Gouider,...,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN
309,2024-05-16,Simona Jasaityte,UTSW,Understanding the Genetic link for Parkinson's...,UT Southwestern Medical Center,Mixed,NaN,Dallas,United States,Vibhash Sharma,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
310,2024-05-16,Simona Jasaityte,ADPAR,Investigation of the genome of patients with a...,Carol Davila University of Medicine and Pharma...,Mixed,NaN,Bucharest,Romania,Bogdan Ovidiu Popescu,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
import pandas as pd
from sqlalchemy import create_engine

# Create an engine instance
engine = create_engine('sqlite:///test.db')

# Query to select all data from the genetic_data table
query = "SELECT * FROM genetic_data"

# Execute the query and load the data into a pandas DataFrame
df = pd.read_sql(query, engine)

# Display the first few rows of the DataFrame
print(df.head())

# Display summary statistics
print(df.describe())

# Display the data types of the columns
print(df.dtypes)

# Filter the data
df_filtered = df[df['city'] == 'Boulder']
print(df_filtered.head())

# # Plot the data
# import matplotlib.pyplot as plt

# df['n_dna_samples_attempted'].hist()
# plt.xlabel('Number of DNA Samples Attempted')
# plt.ylabel('Frequency')
# plt.title('Distribution of DNA Samples Attempted')
# plt.show()

   id study_code monogenic_complex_mixed           city geographic_locality  \
0   1        BCM                 Complex     Houston,TX                 USA
1   2    CORIELL                 Complex     Camden, NJ                 USA
2   3    PDGNRTN                   Mixed     Miami, FL                  USA
3   4        UMD                 Complex  Baltimore, MD                 USA
4   5    PROSPOS                 Complex           Oslo              Norway

   n_dna_samples_attempted  total_qc_pass  callrate_fails  sex_fails  \
0                      809            788               7         12
1                     8982           8718             140         56
2                     4694           3791             239        352
3                      479            441               6         15
4                       96             95               0          1

   het_fails  ...  CAS  MDE  CAH  total  genotyping_complete  \
0          0  ...    5    4    5    788                    0
1          1  ...    8   48  167   8718                    0
2          0  ...   16   21  174   3791                    0
3          0  ...    2    2    2    441                    0
4          0  ...    0    0    0     95                    0

   imputation_panel  imputation_complete  genotypes_shareable  gdpr     site
0            TOPMED                    1                    1     0      NIH
1            TOPMED                    1                    1     0      NIH
2            TOPMED                    1                    1     0  Fulgent
3            TOPMED                    1                    1     0      NIH
4            TOPMED                    1                    1     1  Fulgent

[5 rows x 29 columns]
               id  n_dna_samples_attempted  total_qc_pass  callrate_fails  \
count  311.000000               311.000000     311.000000      311.000000
mean   156.000000               189.302251     175.440514        5.173633
std     89.922189               761.131042     716.178651       24.136081
min      1.000000                 0.000000       0.000000        0.000000
25%     78.500000                 0.000000       0.000000        0.000000
50%    156.000000                 0.000000       0.000000        0.000000
75%    233.500000                19.000000      18.500000        0.000000
max    311.000000              8982.000000    8718.000000      239.000000

        sex_fails   het_fails  duplicates          AFR         AAC  \
count  311.000000  311.000000  311.000000   311.000000  311.000000
mean     4.427653    0.009646    3.559486     8.501608    3.578778
std     22.928650    0.097898   20.679010    91.034339   41.613731
min      0.000000    0.000000    0.000000     0.000000    0.000000
25%      0.000000    0.000000    0.000000     0.000000    0.000000
50%      0.000000    0.000000    0.000000     0.000000    0.000000
75%      0.000000    0.000000    0.000000     0.000000    0.000000
max    352.000000    1.000000  296.000000  1403.000000  723.000000

               AJ  ...         AMR         SAS         CAS         MDE  \
count  311.000000  ...  311.000000  311.000000  311.000000  311.000000
mean     8.562701  ...    2.099678    2.073955    2.906752    1.871383
std     62.169345  ...   15.717251   12.055423   28.430918   12.646159
min      0.000000  ...    0.000000    0.000000    0.000000    0.000000
25%      0.000000  ...    0.000000    0.000000    0.000000    0.000000
50%      0.000000  ...    0.000000    0.000000    0.000000    0.000000
75%      0.000000  ...    0.000000    0.000000    0.000000    0.000000
max    780.000000  ...  195.000000  142.000000  366.000000  197.000000

              CAH        total  genotyping_complete  imputation_complete  \
count  311.000000   311.000000                311.0           311.000000
mean     2.742765   175.440514                  0.0             0.257235
std     22.141293   716.178651                  0.0             0.437814
min      0.000000     0.000000                  0.0             0.000000
25%      0.000000     0.000000                  0.0             0.000000
50%      0.000000     0.000000                  0.0             0.000000
75%      0.000000    18.500000                  0.0             1.000000
max    299.000000  8718.000000                  0.0             1.000000

       genotypes_shareable        gdpr
count           311.000000  311.000000
mean              0.334405    0.202572
std               0.472542    0.402564
min               0.000000    0.000000
25%               0.000000    0.000000
50%               0.000000    0.000000
75%               1.000000    0.000000
max               1.000000    1.000000

[8 rows x 23 columns]
id                          int64
study_code                 object
monogenic_complex_mixed    object
city                       object
geographic_locality        object
n_dna_samples_attempted     int64
total_qc_pass               int64
callrate_fails              int64
sex_fails                   int64
het_fails                   int64
duplicates                  int64
AFR                         int64
AAC                         int64
AJ                          int64
EAS                         int64
EUR                         int64
FIN                         int64
AMR                         int64
SAS                         int64
CAS                         int64
MDE                         int64
CAH                         int64
total                       int64
genotyping_complete         int64
imputation_panel           object
imputation_complete         int64
genotypes_shareable         int64
gdpr                        int64
site                       object
dtype: object
Empty DataFrame
Columns: [id, study_code, monogenic_complex_mixed, city, geographic_locality, n_dna_samples_attempted, total_qc_pass, callrate_fails, sex_fails, het_fails, duplicates, AFR, AAC, AJ, EAS, EUR, FIN, AMR, SAS, CAS, MDE, CAH, total, genotyping_complete, imputation_panel, imputation_complete, genotypes_shareable, gdpr, site]
Index: []

[0 rows x 29 columns]

In [44]:
df

,id,study_code,monogenic_complex_mixed,city,geographic_locality,n_dna_samples_attempted,total_qc_pass,callrate_fails,sex_fails,het_fails,...,CAS,MDE,CAH,total,genotyping_complete,imputation_panel,imputation_complete,genotypes_shareable,gdpr,site
0,1,BCM,Complex,"Houston,TX",USA,809,788,7,12,0,...,5,4,5,788,0,TOPMED,1,1,0,NIH
1,2,CORIELL,Complex,"Camden, NJ",USA,8982,8718,140,56,1,...,8,48,167,8718,0,TOPMED,1,1,0,NIH
2,3,PDGNRTN,Mixed,"Miami, FL",USA,4694,3791,239,352,0,...,16,21,174,3791,0,TOPMED,1,1,0,Fulgent
3,4,UMD,Complex,"Baltimore, MD",USA,479,441,6,15,0,...,2,2,2,441,0,TOPMED,1,1,0,NIH
4,5,PROSPOS,Complex,Oslo,Norway,96,95,0,1,0,...,0,0,0,95,0,TOPMED,1,1,1,Fulgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,FMGC,Mixed,Bordeaux,France,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
307,308,IRAMS,Mixed,Bordeaux,France,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
308,309,GENOT,Mixed,Tunis,Tunisia,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
309,310,UTSW,Mixed,Dallas,United States,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
310,311,ADPAR,Mixed,Bucharest,Romania,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0