In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('data/GenoTracker.csv', header=1)
df_sub = df.loc[:,[
    "Study Code",
    "Monogenic / Complex / Mixed",
    "City",
    "Geographic locality [free text]",
    "DNA samples recieved at site [N]",
    "DNA samples attempted [N]",
    "Total samples passing basic QC [N]",
    "Failed call rates [N < 95%]",
    "Failed sex check [N with contradictory reported versus genetic sex]",
    "Failed contamination and heterozygosity checks [N, outliers for ancestry specific heterozygosity rates]",
    "Duplicate samples [N, IBD estiamtes > 95%]",
    "Removed relatives [N samples related to one or more samples at IBD > 12.5%]",
    "African (AFR)",
    "African admixed (AAC)",
    "Ashkenzai (AJ)",
    "East Asian (EAS)",
    "European (EUR)",
    "Finnish (FIN)",
    "LatinX (AMR)",
    "South Asian (SAS)",
    "Central Asian (CAS)",
    "Middle Eastern (MDE)",
    "Complex Admixture (CAH)",
    "Total",
    "Genotyping complete for the foreseeable future [0 = no, 1 = yes]",
    "Imputation panels(s) [Free text]",
    "Imputation complete for current samples [0 = no, 1 = yes]",
    "Full data [0 = only summary stats, 1 = genotypes sharable]",
    "GDPR [0 = no European restriction, 1 = limited by GDPR]",
    "Site [NIH, Tubingen/DZNE, Fulgent, UCL]"
]]

rename_dict = {
    "Study Code": "study_code",
    "Monogenic / Complex / Mixed": "monogenic_complex_mixed",
    "City": "city",
    "Geographic locality [free text]": "geographic_locality",
    "DNA samples recieved at site [N]": "n_dna_samples_received_at_site",
    "DNA samples attempted [N]": "n_dna_samples_attempted",
    "Total samples passing basic QC [N]": "total_qc_pass",
    "Failed call rates [N < 95%]": "callrate_fails",
    "Failed sex check [N with contradictory reported versus genetic sex]": "sex_fails",
    "Failed contamination and heterozygosity checks [N, outliers for ancestry specific heterozygosity rates]": "het_fails",
    "Duplicate samples [N, IBD estimates > 95%]": "duplicates",
    "Removed relatives [N samples related to one or more samples at IBD > 12.5%]": "related",
    "African (AFR)": "AFR",
    "African admixed (AAC)": "AAC",
    "Ashkenazi (AJ)": "AJ",
    "East Asian (EAS)": "EAS",
    "European (EUR)": "EUR",
    "Finnish (FIN)": "FIN",
    "LatinX (AMR)": "AMR",
    "South Asian (SAS)": "SAS",
    "Central Asian (CAS)": "CAS",
    "Middle Eastern (MDE)": "MDE",
    "Complex Admixture (CAH)": "CAH",
    "Total": "total",
    "Genotyping complete for the foreseeable future [0 = no, 1 = yes]": "genotyping_complete",
    "Imputation panels(s) [Free text]": "imputation_panel",
    "Imputation complete for current samples [0 = no, 1 = yes]": "imputation_complete",
    "Full data [0 = only summary stats, 1 = genotypes sharable]": "genotypes_shareable",
    "GDPR [0 = no European restriction, 1 = limited by GDPR]": "gdpr",
    "Site [NIH, Tubingen/DZNE, Fulgent, UCL]": "site"
}

df_sub.rename(columns=rename_dict, inplace=True)

df_sub.to_csv('data/genotracker_clean.csv', index=False)

In [32]:
# for col in df.columns:
#     print(col)

In [4]:
df_sub.loc[df_sub.AJ.isna()]

AttributeError: 'DataFrame' object has no attribute 'AJ'

In [5]:
df_sub

,study_code,monogenic_complex_mixed,city,geographic_locality,n_dna_samples_received_at_site,n_dna_samples_attempted,total_qc_pass,callrate_fails,sex_fails,het_fails,...,CAS,MDE,CAH,total,genotyping_complete,imputation_panel,imputation_complete,genotypes_shareable,gdpr,site
0,BCM,Complex,"Houston,TX",USA,yes,809.0,788.0,7.0,12.0,0.0,...,5.0,4.0,5.0,788.0,1,TOPMED,1.0,1.0,0.0,NIH
1,CORIELL,Complex,"Camden, NJ",USA,yes,8982.0,8718.0,140.0,56.0,1.0,...,8.0,48.0,167.0,8718.0,1,TOPMED,1.0,1.0,0.0,NIH
2,PDGNRTN,Mixed,"Miami, FL",USA,yes,4694.0,3791.0,239.0,352.0,0.0,...,16.0,21.0,174.0,3791.0,NaN,TOPMED,1.0,1.0,0.0,Fulgent
3,UMD,Complex,"Baltimore, MD",USA,yes,479.0,441.0,6.0,15.0,0.0,...,2.0,2.0,2.0,441.0,1,TOPMED,1.0,1.0,0.0,NIH
4,PROSPOS,Complex,Oslo,Norway,yes,96.0,95.0,0.0,1.0,0.0,...,0.0,0.0,0.0,95.0,NaN,TOPMED,1.0,1.0,1.0,Fulgent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,FMGC,Mixed,Bordeaux,France,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,IRAMS,Mixed,Bordeaux,France,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,GENOT,Mixed,Tunis,Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,UTSW,Mixed,Dallas,United States,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,ADPAR,Mixed,Bucharest,Romania,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_sub.columns

Index(['study_code', 'monogenic_complex_mixed', 'city', 'geographic_locality',
       'n_dna_samples_received_at_site', 'n_dna_samples_attempted',
       'total_qc_pass', 'callrate_fails', 'sex_fails', 'het_fails',
       'Duplicate samples [N, IBD estiamtes > 95%]', 'related', 'AFR', 'AAC',
       'Ashkenzai (AJ)', 'EAS', 'EUR', 'FIN', 'AMR', 'SAS', 'CAS', 'MDE',
       'CAH', 'total', 'genotyping_complete', 'imputation_panel',
       'imputation_complete', 'genotypes_shareable', 'gdpr', 'site'],
      dtype='object')